#!/bin/sh

# Copyright:   (c) 2018, Vladimir Vons, UA
# Author:      Vladimir Vons <VladVons@gmail.com>
# Created:     2021.03.01
# License:     GNU, see LICENSE for more details
# Description:

# Exit on error
set -e

#. /usr/share/debconf/confmodule
Name="py-vRelaySrv"
DirLog="/var/log/$Name"


Install()
{
  apt install --yes --no-install-recommends python3-pip gcc libpython3-dev
  pip3 install setuptools wheel
  pip3 install aiohttp aioodbc aiomysql gmqtt
}


Configure()
{
    # Setup logfile permissions:
    mkdir -p $DirLog

    touch $DirLog/$Name.log
    chmod 640 $DirLog/$Name.log

    if [ -x "/etc/init.d/$Name" ]; then
        update-rc.d $Name defaults
        update-rc.d $Name enable
    fi
}


Debug()
{
  aMode="$1";

  Msg="postinst: $aMode"
  echo $Msg
  echo $Msg >> $DirLog/$Name.log
  #printenv > /$Name.log2
}


Help()
{
fold -s << EOF
/etc/odbcinst.ini
  [MariaDbSQL]
  Description=MariaDb driver
  Driver=libmaodbc.so
  Setup=libmaodbc.so
  Debug=0
  CommLog=1
  UsageCount=1
EOF
}

#Debug $1

case "$1" in
  configure)
    Install
    Configure
    Help
    ;;
  abort-upgrade|abort-remove|abort-deconfigure)
    ;;
  *)
    echo "postinst called with unknown argument '$1'" >&2
    exit 1
    ;;
esac

exit 0
